### ISSUE TITLE
symlink test fails on win8.0 x64 node 0.10.32

### ISSUE THREAD

**Issue by iki** [tkellen/node-liftoff#24]
```
 > mocha -R spec test/index.js
  1) Liftoff buildEnvironment should resolve symlinks if config is one:

      AssertionError: expected 'C:\\Users\\iki\\..js\\node-liftoff\\test\\fixtures\\symlink\\mochafile.js' to equal 'C:\
\Users\\iki\\..js\\node-liftoff\\test\\fixtures\\mochafile.js'
      + expected - actual

      +"C:\\Users\\iki\\..js\\node-liftoff\\test\\fixtures\\mochafile.js"
      -"C:\\Users\\iki\\..js\\node-liftoff\\test\\fixtures\\symlink\\mochafile.js"

    at Context.<anonymous> (C:\Users\iki\..js\node-liftoff\test\index.js:95:33)
    at callFn (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:249:21)
    at Test.Runnable.run (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runnable.js:242:7)
    at Runner.runTest (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:373:10)
    at C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:451:12
    at next (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:298:14)
    at C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:308:7
    at next (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:246:23)
    at Object._onImmediate (C:\Users\iki\AppData\Roaming\npm\node_modules\mocha\lib\runner.js:275:5)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```
See also another test suite error on windows: https://github.com/tkellen/node-liftoff/issues/23.

**Comment by tkellen** [comment]
Pretty sure this is related to gulp/gulpjs#664

**Comment by heikki** [comment]
https://github.com/joyent/node/issues/6342#issuecomment-26214543

> EPERM means 'permission denied.' The default security policy allows only administrators to create symbolic links.

After changing the security settings all tests pass on Win7 virtual machine with v0.12.0, v0.11.16 & v0.10.36.

**Comment by tkellen** [comment]
:+1: thanks @heikki
